### PR TITLE
ensure imagePullPolicy is Always and ability to use optional CronJob to rollout deployment update

### PR DESCRIPTION
**Pull request by chrisahl**
Signed-off-by: Chris Ahl <cahl@redhat.com>

For issue https://issues.redhat.com/browse/CMCS-136

### CODE REVIEW

**Review by robinbobbitt — COMMENTED** [review]
This looks awesome @chrisahl . What do you think about just not deploying the CronJob at all by default, rather than the once a year cron?

**Comment by chrisahl** [comment]
Changes made based on review comments.  If KCP_SYNCER_CRONJOB_SCHEDULE is not defined, the CronJob will not show up on the managed cluster

**Review by robinbobbitt — APPROVED** [review]
Looks great! Not needed atm but we should say the CronJob is not created rather than saying it's disabled (that sounds like it's there but doesn't run). Thanks @chrisahl !

**Pull request merged**
